#pragma once

#ifndef MOTION_WRAPMODES_HPP
#define MOTION_WRAPMODES_HPP

enum Motion_WrapModes
{
	MOTION_INVALID_WRAPMODE = -1,
	MOTION_WRAPMODE_CLAMP,
	MOTION_WRAPMODE_LOOP,
	MOTION_WRAPMODE_PINGPONG,
	NUM_OF_MOTION_WRAPMODES
};
#endif