#pragma once

#ifndef SPECIALCASEOPERATIONS_HPP
#define SPECIALCASEOPERATIONS_HPP

enum SpecialCaseOperations
{
	IS_SAME,
	IS_GREATER_THAN,
	IS_LESS_THAN,
	IS_LESS_THAN_OR_EQUAL_TO,
	IS_GREATER_THAN_OR_EQUAL_TO,
	IS_NOT_EQUAL_TO,
	NUMBER_OF_SPECIALCASEOPERATIONS
};

#endif