#pragma once

#ifndef TILEDEFINITIONSPECIALCASEREQUIREMENT_HPP
#define TILEDEFINITIONSPECIALCASEREQUIREMENT_HPP

enum TileDefinitionSpecialCaseRequirement
{
	TILEDEFINITIONS_ARE_SAME,
	NUMBER_OF_TILEDEFINITIONSPECIALCASEREQUIREMENTS
};

#endif