#pragma once

#ifndef QUESTTRIGGERWHATTODOWITHSTATOPTIONS_HPP
#define QUESTTRIGGERWHATTODOWITHSTATOPTIONS_HPP

enum QuestTriggerWhatToDoWithStatOptions
{
	SET,
	INCREMENT,
	NUMBER_OF_WHAT_TO_DO_WITH_STAT_OPTIONS	
};

#endif