#pragma once


enum PrimitiveType
{
	INVALID_PRIMITIVE_TYPE = -1,
	PRIMITIVE_POINTS,
	PRIMITIVE_LINES,
	PRIMITIVE_TRIANGLES,
	PRIMITIVE_QUADS,
	PRIMITIVE_DYNAMIC_DRAW,
	NUM_PRIMITIVE_TYPES
};
enum VBOusage
{
	STATIC_DRAW,
	NUM_VBO_USAGE_TYPES
};
enum DataType
{
	INVALID_DATA_TYPE = -1,
	BYTE_,
	UNSIGNED_BYTE_,
	SHORT_,
	UNSIGNED_SHORT_,
	INTEGER_,
	UNSIGNED_INTEGER_,
	FLOATING_POINT_,
	TWO_BYTES_,
	THREE_BYTES_,
	FOUR_BYTES_,
	DOUBLE_,
	NUM_OF_DATA_TYPES
};
enum DistanceType
{
	INVALID_DISTANCE_TYPE = -1,
	NEAREST_DISTANCE_TYPE,
	LINEAR_DISTANCE_TYPE,
	REPEAT_DISTANCE_TYPE,
	NUMBER_OF_DISTANCE_TYPES
};
enum TextureType
{
	INVALID_TEXTURE = -1,
	TEXTURE_2D_TYPE,
	TEXTURE_3D_TYPE,
	CUBE_MAP_TYPE,
	NUMBER_OF_TEXTURE_TYPES
};