#pragma once

#ifndef UIWIDGETSTATES_HPP
#define UIWIDGETSTATES_HPP

enum UIWidgetStates
{
	UIWIDGETSTATE_HIDDEN = -1,
	UIWIDGETSTATE_ACTIVE,
	UIWIDGETSTATE_HIGHLIGHTED, //Hovered
	UIWIDGETSTATE_HOVERED = UIWIDGETSTATE_HIGHLIGHTED,
	UIWIDGETSTATE_PRESSED,
	UIWIDGETSTATE_DISABLED,
	UIWIDGETSTATE_NUM_TO_HOLD_DATA_FOR,
	UIWIDGETSTATE_NUM_OF_STATES
};

#endif