#pragma once

#ifndef DEFINEDFEATUREBEHAVIORIDXES_HPP
#define DEFINEDFEATUREBEHAVIORIDXES_HPP

enum DefinedFeatureBehaviorIdxes
{
	INVALID_FEATURE_BEHAVIOR = -1,
	ON_PLACEMENT_FEATURE_BEHAVIOR,
	INTERACTIVE_FEATURE_BEHAVIOR,
	ON_UPDATE_FEATURE_BEHAVIOR,
	NUMBER_OF_DEFIND_FEATURE_BEHAVIOR_TYPES
};

#endif