#pragma once

#ifndef ITEMCAREABOUTGENDERORNOT_HPP
#define ITEMCAREABOUTGENDERORNOT_HPP

enum ItemCareAboutGenderOrNot
{
	DONT_CARE,
	MALE_ONLY,
	FEMALE_ONLY,
	NUMBER_OF_ITEM_CARE_OR_DONT_CARE_OPTIONS
};
#endif